"""empty message

Revision ID: 5af322f1536c
Revises: 
Create Date: 2023-10-27 11:18:32.126395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af322f1536c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('UID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, default=1),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False, default=0),
    sa.Column('gender', sa.Integer(), nullable=False, default=0),
    sa.PrimaryKeyConstraint('UID'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
